FROM php:8.2-fpm

# install utilities + extensions
RUN apt-get update && apt-get install -y \
	zip unzip libpq-dev libonig-dev libzip-dev \
	&& docker-php-ext-install pdo_mysql zip

COPY . /var/www/html
WORKDIR /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --optimize-autoloader

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
